### ISSUE TITLE
'undefined is not an object (evaluating ReactPropTypes.string)'

### ISSUE THREAD

**Issue by ror-y** [twilio/TwilioChatJsReactNative#11]
This shows as soon as I run the project, presumable because of the change introduced in React 15.5.
<img width="415" alt="screen shot 2018-02-24 at 17 57 18" src="https://user-images.githubusercontent.com/10364894/36633373-62c8b878-198c-11e8-88e6-863bbe0703e8.png">

Any quick way around this?

**Comment by digitaldavenyc** [comment]
`PropTypes` is not part of the react core library anymore. This doesn't look like a Twilio issue but an issue with your local code base or some other lib.

**Comment by aleksandrsivanovs** [comment]
I'll check, thanks for report

**Comment by ror-y** [comment]
It runs successfully when I downgrade React to `16.0.0-alpha.12`

**Comment by aleksandrsivanovs** [comment]
seems like yes moved to separate library, https://reactjs.org/docs/typechecking-with-proptypes.html

**Comment by aleksandrsivanovs** [comment]
I've moved to latest react and it seems that all things are fixed now (verified with ios and android)
