### ISSUE TITLE
[login][Error] can't get token

### ISSUE THREAD

**Issue by Riyas-precise** [twilio/TwilioChatJsReactNative#12]
When create client TwilioChatClient.create(token, chatClientConfig.options || {}), Got this Error
![screen shot 2018-03-07 at 3 28 32 pm](https://user-images.githubusercontent.com/6427093/37085954-6a06ceb6-221c-11e8-897d-9aa887840036.png)

![screen shot 2018-03-07 at 3 28 18 pm](https://user-images.githubusercontent.com/6427093/37085953-69b36d0c-221c-11e8-8398-2ce7d38c97cc.png)

How to solve this?

**Comment by aleksandrsivanovs** [comment]
Hi!

seems like you don't have the correct token (or token generator is not available).
quick explanation how to setup the token generator for this repo is here: https://github.com/twilio/TwilioChatJsReactNative#token-provider-and-chat-configuration
