### ISSUE TITLE
Android Backgrounding + shutdown issue

### ISSUE THREAD

**Issue by davidpricedev** [twilio/TwilioChatJsReactNative#14]
There seems to be an issue with this around backgrounding on android plus a shutdown followed by a create.

Relevant Versions:

* "twilio": "^3.11.1"
* "twilio-chat": "^2.1.0",
* "twilio-common": "^0.1.7",
* "react-native": "0.53.3",

Steps to reproduce: 

1. create a new chat client `const firstClient = await TwilioChatClient.create(...);`
2. background the app for a few seconds (switch to a different app, for instance)
3. resume the app (switch back to the app with the chat client running)
4. shutdown the chat client `await firstClient.shutdown();`
5. try to create a new client `const secondClient = await TwilioChatClient.create(...);` - create never returns. Somewhere in its promise chains a promise is never getting resolved.

If you skip steps 2 & 3, then things work as expected, you can create and shutdown client instances repeatedly. I was also able to skip step 4 and create a second client instance after backgrounding.

**Comment by aleksandrsivanovs** [comment]
hi!

thank you for your report. 
I have a question, though: do you use same client options in both `create`s?
there was an issue with versions pre 2.2.0 - you should have used new client options every time.
can you, please, verify that the issue persists when you each time pass new client options object to the `create` method?

(changelog for 2.2.0 is here - the bug about clientoptions is mentioned there: https://www.twilio.com/docs/chat/javascript/changelog#programmable-chat-220-march-13-2018)

**Comment by davidpricedev** [comment]
Yes, creating a new options object every time or upgrading to 2.2.0 seems to resolve the issue. Thanks!
