### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by markmadlangbayan** [twilio/TwilioChatJsReactNative#17]
Hello,
How do we get about to generating these keys below?  FYI, I don't know much about Twillio, but we are willing to give it a try.  Thanks in advance!

```
{
  "tokenGenerator": {
    "signingKeySid": "SKxxx",
    "signingKeySecret": "xxx",
    "fcm": "CRxxx",
    "apns": "CRxxx"
  }
}
```

**Comment by berkus** [comment]
Hi,

Signing key SID and secret are the special signing keys created [here](https://www.twilio.com/console/chat/dev-tools/api-keys), this page provides both the key and sid for the key, you can control key validity there.

fcm and apns are sids of credentials created in `Notify > Push Credentials` in your [Twilio account](https://www.twilio.com/console/notify/credentials).

**Comment by aleksandrsivanovs** [comment]
I will close this issue as answer has been given and no further questions received
