### ISSUE TITLE
Add example of unregisterFCMToken / deregisterWithNotificationToken

### ISSUE THREAD

**Issue by alexcchan** [twilio/TwilioChatJsReactNative#19]
It would be good to add a code binding for

`unregisterFCMToken` (Android)
`deregisterWithNotificationToken` (iOS)

**Comment by aleksandrsivanovs** [comment]
that was some misunderstanding. To unregister from pushes one should call `unsetPushRegistrationId` method (http://media.twiliocdn.com/sdk/js/chat/releases/3.1.0/docs/Client.html#unsetPushRegistrationId__anchor)
