### ISSUE TITLE
Can't connect to twilsock

### ISSUE THREAD

**Issue by acoulon99** [twilio/TwilioChatJsReactNative#20]
Has anyone encountered this? I've reproduced it on this project as well as my own. I confirmed it occurs on the iOS simulator as well as on a physical Android device.

![image](https://user-images.githubusercontent.com/9921114/47571827-1677a500-d8ff-11e8-8d51-3ec2a0a18548.png)

**Comment by keesvandieren** [comment]
@acoulon99  we have this error too. How did you resolve it?

**Comment by adilosa** [comment]
Also getting this error intermittently. Reloading the React app seems to get past it temporarily.

**Comment by aleksandrsivanovs** [comment]
there are two most common cases which can cause this problem:
1) actual network is down - i.e. it just can't connect to our transport backend
2) something is very wrong with token provided to the Chat

**Comment by diivyu** [comment]
I am having the same error.
Do we have any solution for this?
