### ISSUE TITLE
Issues with channel in release build

### ISSUE THREAD

**Issue by jessicatan83** [twilio/TwilioChatJsReactNative#21]
Hi, I've found that the Twilio library keeps on failing most of the time after **channel.getMessages()** is called in a release build (Android). It works okay on debug mode when I run react-native run-android, but once I package it all up into an apk, multiple errors occur. 

Any thoughts? Hope someone can help.

**Chat Session E:", "Failed to add a command to the session", 
Chat Members E:', 'Failed to get roster object for channel', 'CHbdaf37d0580144969a346d3fc8ff5a85', [f: disconnected (status: 0, code: 0)]
Chat Channel E:', 'Failed to subscribe on channel objects', 'CHbdaf37d0580144969a346d3fc8ff5a85', [f: disconnected (status: 0, code: 0)]**

`11-21 16:54:34.305 20512-20566/? E/ReactNativeJS: '2018-11-21T03:54:34.305Z Chat Session E:', 'Failed to add a command to the session', [f: disconnected (status: 0, code: 0)]
11-21 16:54:34.310 20512-20566/? E/ReactNativeJS: '2018-11-21T03:54:34.310Z Chat Session E:', 'Failed to add a command to the session', [f: disconnected (status: 0, code: 0)]
11-21 16:54:34.319 20512-20567/? E/unknown:ReactNative: console.error: "2018-11-21T03:54:34.305Z Chat Session E:", "Failed to add a command to the session", {"name":"f","message":"disconnected (status: 0, code: 0)","status":0,"code":0,"line":88,"column":1893,"sourceURL":"index.android.bundle"}, stack:
    value@1471:2532
    <unknown>@1583:3706
    f@86:155
    <unknown>@86:882
    <unknown>@89:1815
    y@89:657
    C@89:1021
    callImmediates@89:3216
    value@17:4419
    <unknown>@17:2810
    value@17:4111
    value@17:2780
    value@17:2395
11-21 16:54:34.327 20512-20567/? E/unknown:ReactNative: console.error: "2018-11-21T03:54:34.310Z Chat Session E:", "Failed to add a command to the session", {"name":"f","message":"disconnected (status: 0, code: 0)","status":0,"code":0,"line":88,"column":1893,"sourceURL":"index.android.bundle"}, stack:
    value@1471:2532
    <unknown>@1583:3706
    f@86:155
    <unknown>@86:882
    <unknown>@89:1815
    y@89:657
    C@89:1021
    callImmediates@89:3216
    value@17:4419
    <unknown>@17:2810
    value@17:4111
    value@17:2780
    value@17:2395
11-21 16:54:52.849 631-631/? E/slim_daemon: [NDK] getTimeUpdate: Invalid Sensor-to-AP offset.
11-21 16:55:22.853 631-631/? E/slim_daemon: [NDK] getTimeUpdate: Invalid Sensor-to-AP offset.
11-21 16:55:52.863 631-631/? E/slim_daemon: [NDK] getTimeUpdate: Invalid Sensor-to-AP offset.
11-21 16:56:13.603 6695-20363/? E/SQLiteCastStore: Skip saving CastDeviceInfo: "Nearby device" (__cast_nearby___V_57c3de2c-054e-4c4b-bb0d-0ba9666c144d)
11-21 16:56:22.870 631-631/? E/slim_daemon: [NDK] getTimeUpdate: Invalid Sensor-to-AP offset.
11-21 16:56:26.612 10731-10810/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=110, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ]
11-21 16:56:26.716 10858-10870/? E/RecentsTaskLoader: Unexpected null component name or activity info: ComponentInfo{com.ushare.mobile.rider/com.ushare.mobile.rider.MainActivity}, null
    Unexpected null component name or activity info: ComponentInfo{com.ushare.mobile.rider/com.ushare.mobile.rider.MainActivity}, null
11-21 16:56:26.722 10858-10870/? E/RecentsTaskLoader: Unexpected null component name or activity info: ComponentInfo{com.ushare.mobile.rider/com.ushare.mobile.rider.MainActivity}, null
11-21 16:56:27.116 6626-20999/? E/ctxmgr: [ProducerStatusImpl]updateStateForNewContextData: inactive, contextName=7
11-21 16:56:27.632 6626-6626/? E/BeaconBle: Scan couldn't start for Places
11-21 16:57:26.240 6686-19856/? E/GeofenceHelper: Failed: remove geofences by PendingIntent
11-21 16:58:58.574 555-626/? E/installd: Failed to delete /data/app/vmdl94025863.tmp: No such file or directory
11-21 16:59:00.165 615-1879/? E/OMXNodeInstance: getConfig(0xeac0f000:google.mp3.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
11-21 16:59:00.259 615-2201/? E/OMXNodeInstance: getConfig(0xeafa3140:google.mp3.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
11-21 16:59:00.385 615-2201/? E/OMXNodeInstance: getConfig(0xeac0f000:google.mp3.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
11-21 16:59:00.425 615-683/? E/OMXNodeInstance: getConfig(0xeafa3560:google.mp3.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
11-21 16:59:02.281 21239-21239/? E//system/bin/webview_zygote32: failed to make and chown /acct/uid_99023: Permission denied
11-21 16:59:02.281 21239-21239/? E/Zygote: createProcessGroup(99023, 0) failed: Permission denied
11-21 16:59:02.322 21263-21263/? E/asset: setgid: Operation not permitted
11-21 16:59:05.401 21170-21221/? E/RNKeychainManager: No entry found for service: 
11-21 16:59:05.416 21170-21221/? E/RNKeychainManager: No entry found for service: 
11-21 16:59:29.631 368-372/? E/QC-time-services: Receive Passed == base = 13, unit = 1, operation = 2, result = 0
11-21 16:59:29.632 619-645/? E/QC-time-services: Daemon: Time-services: Waiting to acceptconnection
11-21 16:59:29.633 619-645/? E/QC-time-services: Daemon: Time-services: Waiting to acceptconnection
11-21 16:59:29.684 368-372/? E/QC-time-services: Receive Passed == base = 13, unit = 1, operation = 2, result = 0
11-21 16:59:29.684 619-645/? E/QC-time-services: Daemon: Time-services: Waiting to acceptconnection
11-21 16:59:29.685 619-645/? E/QC-time-services: Daemon: Time-services: Waiting to acceptconnection
11-21 16:59:29.698 368-372/? E/QC-time-services: Receive Passed == base = 13, unit = 1, operation = 2, result = 0
11-21 16:59:29.699 619-645/? E/QC-time-services: Daemon: Time-services: Waiting to acceptconnection
11-21 16:59:29.700 619-645/? E/QC-time-services: Daemon: Time-services: Waiting to acceptconnection
11-21 16:59:35.570 368-372/? E/QC-time-services: Receive Passed == base = 13, unit = 1, operation = 2, result = 0
11-21 16:59:35.570 619-645/? E/QC-time-services: Daemon: Time-services: Waiting to acceptconnection
11-21 16:59:35.573 619-645/? E/QC-time-services: Daemon: Time-services: Waiting to acceptconnection
11-21 16:59:35.591 368-372/? E/QC-time-services: Receive Passed == base = 13, unit = 1, operation = 2, result = 0
11-21 16:59:35.591 619-645/? E/QC-time-services: Daemon: Time-services: Waiting to acceptconnection
11-21 16:59:35.592 619-645/? E/QC-time-services: Daemon: Time-services: Waiting to acceptconnection
11-21 17:00:46.159 21170-21220/? E/ReactNativeJS: '2018-11-21T04:00:46.158Z Chat Members E:', 'Failed to get roster object for channel', 'CHbdaf37d0580144969a346d3fc8ff5a85', [f: disconnected (status: 0, code: 0)]
11-21 17:00:46.170 21170-21220/? E/ReactNativeJS: '2018-11-21T04:00:46.169Z Chat Channel E:', 'Failed to subscribe on channel objects', 'CHbdaf37d0580144969a346d3fc8ff5a85', [f: disconnected (status: 0, code: 0)]
11-21 17:00:46.171 21170-21220/? E/ReactNativeJS: '2018-11-21T04:00:46.171Z Chat Channel E:', 'Failed to subscribe on channel objects', 'CHbdaf37d0580144969a346d3fc8ff5a85', [f: disconnected (status: 0, code: 0)]
11-21 17:00:46.185 21170-21221/? E/unknown:ReactNative: console.error: "2018-11-21T04:00:46.158Z Chat Members E:", "Failed to get roster object for channel", "CHbdaf37d0580144969a346d3fc8ff5a85", {"name":"f","message":"disconnected (status: 0, code: 0)","status":0,"code":0,"line":88,"column":1893,"sourceURL":"index.android.bundle"}, stack:
    value@1471:2532
    <unknown>@1486:3648
    f@86:155
    <unknown>@86:882
    <unknown>@89:1815
    y@89:657
    C@89:1021
    callImmediates@89:3216
    value@17:4419
    <unknown>@17:2810
    value@17:4111
    value@17:2780
    value@17:2395
11-21 17:00:46.198 21170-21221/? E/unknown:ReactNative: console.error: "2018-11-21T04:00:46.169Z Chat Channel E:", "Failed to subscribe on channel objects", "CHbdaf37d0580144969a346d3fc8ff5a85", {"name":"f","message":"disconnected (status: 0, code: 0)","status":0,"code":0,"line":88,"column":1893,"sourceURL":"index.android.bundle"}, stack:
    value@1471:2532
    <unknown>@1485:6655
    k@88:3838
    <unknown>@88:4877
    <unknown>@88:4020
    l@1485:946
    f@86:155
    <unknown>@86:882
    <unknown>@89:1815
    y@89:657
    C@89:1021
    callImmediates@89:3216
    value@17:4419
    <unknown>@17:2810
    value@17:4111
    value@17:2780
    value@17:2395
11-21 17:00:46.206 21170-21221/? E/unknown:ReactNative: console.error: "2018-11-21T04:00:46.171Z Chat Channel E:", "Failed to subscribe on channel objects", "CHbdaf37d0580144969a346d3fc8ff5a85", {"name":"f","message":"disconnected (status: 0, code: 0)","status":0,"code":0,"line":88,"column":1893,"sourceURL":"index.android.bundle"}, stack:
    value@1471:2532
    <unknown>@1485:6655
    k@88:3838
    <unknown>@88:4877
    <unknown>@88:4020
    l@1485:946
    f@86:155
    <unknown>@86:882
    <unknown>@89:1815
    y@89:657
    C@89:1021
    callImmediates@89:3216
    value@17:4419
    <unknown>@17:2810
    value@17:4111
    value@17:2780
    value@17:2395`

**Comment by aleksandrsivanovs** [comment]
Hi! 

that seems like network disconnect. 
we have fixed multiple problems regarding network connect/reconnect in the latest couple of versions of twilio-chat. 

which version of twilio-chat are you using?

**Comment by jessicatan83** [comment]
Thank you, Aleksandrs. I appreciate you replying so quickly.
I’m using 3.1.0 but I also tried 3.0.2 earlier, but seemed to behave the same.

It appears to successfully go through token retrieval, channel initialisation, events subscription, and then breaks at the getMessages() part. Ive seen it throw a “SyncError" once as well, but couldn’t find any information on it online.

I’m currently on a trial account, while my boss sets up a proper account. Do you know if that could be a cause? 

Thanks and regards,
Jessica

**Comment by aleksandrsivanovs** [comment]
can you, please, enable debug logging and send me the log?
(preferably with small channel count and only one additional call to getMessages() - for easier debug).

we have created support ticket, you should have got the email by now with instructions how to attach log file there.

**Comment by aleksandrsivanovs** [comment]
we have released new twilio-chat version 3.2.3 in April - it is the fix the underlaying networking issue you are having. 
Can you, please, re-check with latest twilio-chat ?

**Comment by jessicatan83** [comment]
Thank you. We will update and see how it goes. Have a great weekend.

**Comment by aleksandrsivanovs** [comment]
Hi!

Just checking in - any news with updated lib?

**Comment by jessicatan83** [comment]
Hi Aleksandrs,

We've updated and everything seems to be okay so far. We haven't re-done
any proper performance tests or failure stats on it recently so I can't say
in detail. But everything looks good for now, everything seems to be smooth
and stable. Thank you so much again, for your help on this!

Regards,
Jessica

**Comment by aleksandrsivanovs** [comment]
sorry it took so much time - there was some under the hood changes to the networking and we had hard time catching and fixing it.

I'll close the ticket then
