### ISSUE TITLE
Android: 'Unhandled promise rejection', { [TypeError: Incompatible receiver, Map required!]

### ISSUE THREAD

**Issue by stanshivam** [twilio/TwilioChatJsReactNative#22]
I'm getting the error 'Unhandled promise rejection', { [TypeError: Incompatible receiver, Map required!]
And app is crashing in release build.

Relevant Versions:
"twilio-chat": "^3.0.2",
"react-native": "0.53.3"

**Comment by stanshivam** [comment]
The root cause here is that RN fails to correctly polyfill Map in the Android environment (the issue linked above). So, we can explicitly load that polyfill, and also Set/Symbol for good measure.

Alright! , the fix for your this is to add the following to `index.js`:
```
import 'core-js/es6/symbol';
import 'core-js/es6/set';
import 'core-js/es6/map';
```

**Comment by prameetc** [comment]
Can you let me know how you exactly solved this? I am facing the same issue @stanshivam. How should I add these dependencies?
