### ISSUE TITLE
Can't connect to twilsock

### ISSUE THREAD

**Issue by KalebMatthews** [twilio/TwilioChatJsReactNative#26]
I followed the Twilio Documentation exactly and looked at this example and have everything generating correctly but every time I go to create the Client I get the Can't connect to twilsock error. I read the responses in https://github.com/twilio/TwilioChatJsReactNative/issues/20 and I have a strong connection to the internet and the token is being generated as per the specifications of the documentation by my backend. I feel like I am missing something simple but I have been over the doc 100 times and it is exactly as specified. 

I am generating the token with the proper ChatGrant and with proper token arguments. I thought it might be user base at one point and added code to create a user if one did not exist yet for the user logged into our system.

Suggestions and advice appreciated.

**Comment by KalebMatthews** [comment]
I found the issue. The issue resided in our C# backend. We were pushing the expiration date to 24 hours in the future but the value was not being stored correctly in the JWT. JWT said the exp time was a negative number (Jan. 1st, 0001 to be exact). To solve this we just removed the expiration date since nothing seemed to work there and we'll put more weight on the renewing token code.

Hope this helps someone else who runs into this.

**Comment by abigoroth** [comment]
hi.. I'm still having this issue

Uncaught (in promise) Error: Can't connect to twilsock ----  twilio-chat.min.js:204

**Comment by diivyu** [comment]
I am having the same error.
Do we have any solution for this?

**Comment by KalebMatthews** [comment]
My last comment has my solution. Have you checked that to confirm it is the same issue? If it is not then you might want to open a new ticket or provide more details as to what you are seeing.
