### ISSUE TITLE
Getting "Unhandled promise rejection" name: SyncError

### ISSUE THREAD

**Issue by MattJLeach** [twilio/TwilioChatJsReactNative#29]
I am getting "Unhandled promise rejection" name: SyncError when I try to use TwilioChatClient.create. I have followed your documentation as well as this example app and can't figure out what is going on.

I am handling all promises with catch blocks so can't figure out why I'm getting this error

**Comment by MattJLeach** [comment]
After a few hours of looking at this I realised that my server was passing the token without calling `toJwt()` on it which was causing the issue. If anyone else is getting this, check your backend. Will close issue.

**Comment by arthedza** [comment]
> After a few hours of looking at this I realised that my server was passing the token without calling `toJwt()` on it which was causing the issue. If anyone else is getting this, check your backend. Will close issue.

Hello Matt! Did you get this error when creating chat client and it's creating was interrupted? Or you have created the client successfully but you can not get messages or get chat members or make other chat client interactions?

**Comment by umeshsgh82** [comment]
> > After a few hours of looking at this I realised that my server was passing the token without calling `toJwt()` on it which was causing the issue. If anyone else is getting this, check your backend. Will close issue.
> 
> Hello Matt! Did you get this error when creating chat client and it's creating was interrupted? Or you have created the client successfully but you can not get messages or get chat members or make other chat client interactions?

I'm also getting the same error.

**Comment by berkus** [comment]
Please create a new issue with logs if you're getting an error. It's hard to guess if you're getting the same error for the same reason or not. Do pay attention to what @MattJLeach wrote and check you're receiving correct token as well.
