### ISSUE TITLE
lastConsumedMessageIndex always 'undefined'

### ISSUE THREAD

**Issue by r0b0t3d** [twilio/TwilioChatJsReactNative#32]
Hi,
I am implementing [Message Consumption Horizon](https://www.twilio.com/docs/chat/consumption-horizon) to achieve `read status`. But it always `undefined`.
```javascript
function memberUpdated(member) {
    console.warn("updateReasons", member.updateReasons);
    console.warn('identity ' + member.identity,
                '\nlastConsumedMessageIndex ' + member.lastConsumedMessageIndex, 
                '\nlastConsumptionTimestamp ' + member.lastConsumptionTimestamp);
}

currentChatChannel.on('memberUpdated', memberUpdated);
```
![image](https://user-images.githubusercontent.com/8109285/63565197-2c430e80-c592-11e9-84d2-4e8db6145cd2.png)

**Comment by aleksandrsivanovs** [comment]
Hi!

that actually means that no messages are consumed by this member.
do you have any more information you can provide (i.e. making sure that messages are consumed and how do you do that and when does this update comes?

Aleksandrs
