### ISSUE TITLE
Create Client and onMessage events are super slow

### ISSUE THREAD

**Issue by amanmobicules** [twilio/TwilioChatJsReactNative#35]
The twilio chat is really slow. Create client takes almost 10 - 15 second to resolve the promise and also while sending a message the UI freezes and onMessage event get fired in 4 - 5 seconds.

When we debug the build in React native , everything works smooth. But for Release build or if React Native debug is turned off, everything just slows down

Here are the versions we are using 

React native version : 0.59.5
Twilio Chat : 3.3.3

Is there any wrapper which we can use to call Native SDKs rather than using the Twilio-chat npm. I think Native will be the best option here.

**Comment by radicalization** [comment]
i have problem with touchable components they are blocked until notification/message is not received...

**Comment by kushalshah-invx** [comment]
I have the same problem. When react-native debug is on channel listing takes hardly 3-4 seconds but for release builds it takes approx 50seconds to 1 minute. @amanmobicules Have found solution of it?

**Comment by berkus** [comment]
Please do not log twilio chat objects entirely into the debug logs - they are objects with some deep links and dumping them to React log may slow the app down a lot.
