### ISSUE TITLE
Chat notifications and notify integration

### ISSUE THREAD

**Issue by dzianis-monich** [twilio/TwilioChatJsReactNative#38]
Hi! is it possible listen notifications from chat (like messageAdded) and notifications sent from back-end via twilio notify?

**Comment by Gapur** [comment]
Hi dzianis-monich, I think yes, Twilio-chat has the event `pushNotification`. This event is fired when the client received (and parsed) push notification via one of push channels (apn, gcm, fcm). http://media.twiliocdn.com/sdk/js/chat/releases/4.0.0/docs/Client.html#event:pushNotification__anchor

**Comment by ayesha-we-over-i** [comment]
Shouldn't this event fire on the channel because that's where messages get sent? Why is it getting fired on the client?

**Comment by ayesha-we-over-i** [comment]
I want to be able to get a notification when a chat message is sent on a channel using sendMessage(). How do I do that?

**Comment by berkus** [comment]
@ayesha-we-over-i i believe you should just subscribe to the notification, subscribe to client.pushNotification  event and probably also be disconnected from twilio, but i'm not sure about the last step. I believe it will work only if  you have no active connection, but i may be wrong.

If you're connected just subscribe to the `messageAdded` event and you'll get the new messages notification from twilio.

**Comment by ayesha-we-over-i** [comment]
First of all, wow! Thanks for the speedy reply, @berkus. Also, I am subscribed to client.pushNotification but its on a separate js file than from where I send messages (a chat page in the UI). I am also subscribed to messageAdded and all that works, but not sure about how to make it trigger a notification. From what I understand:

- `<static> parsePushNotification(notificationPayload)` to GET notification as PushNotification object.
- `setPushRegistrationId(channelType, registrationId)` to register for push notifications where registrationId is a ‘gcm’, ‘apn’ or ‘fcm’ push notification id.
- `handlePushNotification(notificationPayload)` to SEND notifications. This emits the event pushNotification  and takes a notificationPayload .

These are all client functions so not sure how to make them work with chat?

**Comment by ayesha-we-over-i** [comment]
Also, why would I be disconnected from twilio for this to work?

**Comment by berkus** [comment]
@ayesha-we-over-i so, to register your device for push registrations you need to call

`setPushRegistrationId('fcm', 'token received from the fcm registration listener');`

or

`setPushRegistrationId('apn', 'token received from the apns registration listener');`

you cannot SEND push notifications yourself, it's not a job for Chat client.

You will receive the push notification in your notification listener (i.e. through a package like [react-native-push-notification](https://www.npmjs.com/package/react-native-push-notification) - it has examples and manual).
You can then use `parsePushNotification()`  to extract interesting details about the push notification from the incoming payload.

You need to be disconnected from the twilio chat service in order to receive push notifications, because whilst you are connected you get the same notifications over websocket (it's faster).

**Comment by ayesha-we-over-i** [comment]
Okay this helps. I have a few more questions, please bear with me. 

When is the `pushNotification` event triggered? How will Firebase/Twilio know when to trigger a notification? Will the following log something if a message is sent by someone else in one of the chatClient's channels (assuming we are disconnected to the chat service)?


```
chatClient.on("pushNotification", (notificationPayload) => {
              console.log('notificationPayload', notificationPayload);
            });

```

Also, I'd need to set `chatClient.reachabilityEnabled` to `true` right?

**Comment by berkus** [comment]
The `pushNotification` event will be triggered when you feed the notification payload to `client.handlePushNotification()` function. It is not strictly necessary to use.

Reachability must be enabled via your Service Instance configuration, this is not done from the SDK.

**Comment by ayesha-we-over-i** [comment]
And must reachability be enabled for any of this to work? So if it's not necessary to use, is there any time that `pushNotification` will be triggered without calling `client.handlePushNotification()`? I am not able to connect how I will trigger the `pushNotification` event when someone sends a message on a conversation in a client.

**Comment by berkus** [comment]
@ayesha-we-over-i no, it won't. it's  just a convenience signal so you can  decouple your push handling and the actual FCM/APNS listener.
