### ISSUE TITLE
Twilio Chat WebSocket SyncError: disconnected (status: 0, code: 0)

### ISSUE THREAD

**Issue by arthedza** [twilio/TwilioChatJsReactNative#39]
`"Read error: ssl=0xcaf5a948: I/O error during system call, Connection reset by peer"`
Hello! I'm getting this WebSocket error event after twilio.sync.event (event_type: "subscription_established"). Am I doing something wrong on the front-end? Or there are some issues with my backend? Is this an SSL/TLS Handshake Error?

**Comment by neildevas** [comment]
facing this issue as well in Twilio-chat for web.
