### ISSUE TITLE
Send Notification to Twilio

### ISSUE THREAD

**Issue by RUIFERNANDE5** [twilio/TwilioChatJsReactNative#4]
Hey, thank you for this repo, which already gave me big hints on how to implement a chat with Twilio and RN, however I am now implementing the push notification system.
I can handle local notifications, can receive notifications from the FireBase console (android) etc. 
I just can't figure out how to send a notification to Twilio on message send?
As I understand the notification, when login in to Twilio we should use the method `setPushRegistrationId ` to register to the "push notifications listener", and we should be sending  the notifications to the channel itself. Am I correct? But which method should I call on `sendMessage` method? 

Thanks in advance.

**Comment by aleksandrsivanovs** [comment]
Hi!

that's awesome, that this repo is helping people (that was our main intention with it :))

Notifications regarding new messages are sent from our (Twilio) backend if you have push notifications configured for given chat service.

so, in a nutshell you have to do two things:
1) ensure that your client is registering for _receiving_ push notifications (as you have correctly mentioned, via `setPushRegistrationId`)
2) configure your service instance to send push notifications on different events
a) here is some documentation how to set it up through REST API: https://www.twilio.com/docs/api/chat/guides/push-notification-configuration
b) you can change the push notifications configuration through Twilio's Web Console as well: https://www.twilio.com/console/chat/services as well, selecting target chat service and then going to push configuration section

If you have configured push notifications correctly, then for sending message (and other push events) it's happening transparently for the clients - i.e. you will use the same commands (i.e. simple `sendMessage` in mentioned case) and then our backend based on the configuration you've set will decide if push is needed to be sent and what's it's format.

Hope this helps. 

P.S. Also, you can contact our Twilio support engineers through support@twilio.com.
