### ISSUE TITLE
Twilio chat, how set sum of chats to notification _bageCount

### ISSUE THREAD

**Issue by spalmertwilio** [twilio/TwilioChatJsReactNative#40]
Opened from:
https://stackoverflow.com/questions/60128566/twilio-chat-how-set-sum-of-chats-to-notification-bagecount
and Support Request Number 3698920

Short description: I get push notification from Twilio chat. But in my app I use 4 different chats (channels). So when I get field "badge" from notification it just show count of chats with new messages, but no amount of messages.

How can I get the sum of unread messages from all chats?

More info:

- I use react-native 0.61.2 but I write native code too;
- During the work I have used this tutorial [TwilioChatReactNative](https://github.com/twilio/TwilioChatJsReactNative);
- For indicating unread messages I use [Message Consumption Horizon](https://www.twilio.com/docs/chat/consumption-horizon);
- The way of connection to chat (only react part) the close to this [Connect to chat](https://www.twilio.com/blog/2017/10/implement-chat-javascript-nodejs-react-apps.html);
- In theory, I can get set the badge myself, but for me, this function doesn't work in the background;

PushNotificationIOS.setApplicationIconBadgeNumber

- Also, I have tried to use this library react-native-notification but it didn't help too.
- I subscribe to pushNotification with this method

client.setPushRegistrationId('apn', token);

- When I use Twilio Notify and set "badge" by hand all work good, but notification from chat Twilio do by myself.

Summary: I need one decision from this list (or something else, I open for offers):

- Twilio sends me the sum of unread messages from all chat channels;
- The way to update the "badge" while in the background;
- The way of subscribing to channels to get the sum of messages in "badge".

Thanks to everyone who will respond

**Comment by berkus** [comment]
Badge count only shows a number of unread chats.

To get total number of unread messages you will have to open each channel and get number of unread messages from it, then sum it up. This is going to be very expensive in time spent on network operations (each channel unread count request is a separate network request) so use only if absolutely need to.

**Comment by nikita-filimonau** [comment]
Ok, but how I can put this number to push notification?
IOS system just takes "bage" from notification, and I don't have any way how to change it on device in background.
About backend side, twilio-chat generate push notification about new messages by himself. And I don't have any influence on this process.

**Comment by lakshmisanthi** [comment]
Any solution?

**Comment by berkus** [comment]
This is currently not supported by Twilio Chat service. 

It will probably be supported in the future but I dont have the ETA for this.

**Comment by axeljeremy7** [comment]
```// @flow
async function setUnreadCount(channel: Channel, chatDispatch) {
    try {
        if (channel) {
            let num = await channel.getUnconsumedMessagesCount();
            if (num) {
               
                chatDispatch({type: chatActions.setNotifications, channel: channel, num: num});
            } else {

                chatDispatch({type: chatActions.setNotifications, channel: channel, num: 0});
            }
        }
    } catch (error) {
        report(error, `${channel.friendlyName} getUnconsumedMessagesCount()`, 'ERROR');
        
        chatDispatch({type: chatActions.setNotifications, channel: channel, num: 0});
    }
}```

inside my dispatch i reduce the sum from each channel
