### ISSUE TITLE
Can I use https://www.npmjs.com/package/twilio-chat in react native app?

### ISSUE THREAD

**Issue by antmanstar** [twilio/TwilioChatJsReactNative#46]
Hello everyone.
I am developing the react native app using twilio.
Actually so far, I developed the web version of site using twilio chat api and sdk.
But I faced issue while I build react native app because of lacks of my react native & twilio skill.
So I am writing this proposal to ask help of kind and respectful everyone here.

So My question is..
1. Can I use https://www.npmjs.com/package/twilio-chat in the react native app?
2. Can I refer some of your code base even small part of code?
3. Actually TwilioChatJsReactNative is not a npm, this is just example of code. Is there any npm version of this?

Please help poor me. 
Best regards..
Kok..

**Comment by Gray-Wind** [comment]
Hello,

1. Yes, this is the library you should use for building your React Native application.
2. Feel free to do it.
3. Yes, it is a demo project, which purpose is to help you to understand how to build simple chat application using `twilio-chat.js` package. We do not provide any UI for this library at the moment.

**Comment by antmanstar** [comment]
@Gray-Wind thanks for your kind help.
I will try to use `tilwio-chat.js` in my react native app.
really appreciated.

**Comment by Gray-Wind** [comment]
I will close this ticket, feel free to open a new one in case of any questions.

**Comment by antmanstar** [comment]
thanks @Gray-Wind again.
twilio-chat.js works well in my react native.
I am really appreciated.
