### ISSUE TITLE
 Background messages only work if the message priority is set to 'high'

### ISSUE THREAD

**Issue by kcsuyog** [twilio/TwilioChatJsReactNative#47]
I have been using twilio with react native android for chat notification using fcm . But I found out that twilio sends fcm data only message for chat events as a low priority. I cannot send push notification on getting fcm data message while app is in background  since the message priority is not high. Thus I get a Not allowed to start service Intent issue. Has anyone faced this problem ?  is there any way to increase priority for fcm notification in twilio?

**Comment by rafalgogol12** [comment]
Hey Twilio! Any ideas? The problem still exists on android.

**Comment by leshek-pawlak** [comment]
Yes, I have the same problem right now.

**Comment by griffinshuth** [comment]
has anyone able to solve this?

**Comment by ummoybiswas** [comment]
I am facing the same issue. Has anyone been able to solve this issue?
