### ISSUE TITLE
How to run this repo

### ISSUE THREAD

**Issue by tapannathvani** [twilio/TwilioChatJsReactNative#48]
Hello,

We have downloaded this but there is no any proper documentation like how to use it? can you please provide us some other way to use twilio chat library for react native?

**Comment by berkus** [comment]
Look at [Running the app](https://github.com/twilio/TwilioChatJsReactNative#running-the-app) section in the readme?

**Comment by tapannathvani** [comment]
I have followed it but i am facing error.

`Token provider listening on port 3002!
(node:7469) UnhandledPromiseRejectionWarning: #<Object>
(node:7469) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7469) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by yogitaV-dev** [comment]
Hello , I am facing the same issue to run this repo for android plateform. Can you please give the proper documentation for integration.

**Comment by canozmen** [comment]
Hi folks,

Switching to latest LTS version of node (14.15.1) with nvm worked for me on Windows, but now the react native part won't start.

Which node version should we target for both the app and server?

Thanks.
