### ISSUE TITLE
How can i send messages?

### ISSUE THREAD

**Issue by pkpardeep482** [twilio/TwilioChatJsReactNative#49]
spent 2-3 hours, but i was not able to find any function to send messages. Can someone please help me

**Comment by berkus** [comment]
Hi, what about [sendMessage](https://github.com/twilio/TwilioChatJsReactNative/blob/c2cb6da9946a48997c5b31988a2b3069dfb63f49/__tests__/messages.js#L68)?

**Comment by pkpardeep482** [comment]
channel.sendMessage() returns undefined.

**Comment by berkus** [comment]
[According to the docs, it shouldn't](https://media.twiliocdn.com/sdk/js/chat/releases/3.4.0/docs/Channel.html#sendMessage__anchor)

Can you provide logs?

**Comment by pkpardeep482** [comment]
Ok i will paste logs here. But by using this code 

but as of now my code is like this 
import {Client as TwilioChatClient} from 'twilio-chat';
  TwilioChatClient.create(token, {})
      .then((client) => {client.join("room-id"); client.sendMessage("dummy message")})


which return sendMessage is undefined

**Comment by berkus** [comment]
And that is correct - `Client` does not have a `sendMessage` method.

Sending message is operation possible only inside a channel.

**Comment by pkpardeep482** [comment]
How can i achieve that ? is there any documentation for this ?

**Comment by berkus** [comment]
Yes, for example a [demo app here](https://github.com/twilio/twilio-chat-demo-js/) and [official documentation here](https://media.twiliocdn.com/sdk/js/chat/releases/3.4.0/docs/).

**Comment by pkpardeep482** [comment]
ok i will try and get back to you

**Comment by berkus** [comment]
@pkpardeep482 did you get it working?

**Comment by ControlAndC** [comment]
@berkus @pkpardeep482 

I am not able to get a way of sending message to a joined channel, Can you provide some help.

A code snippet will surely help.

Thanks

**Comment by berkus** [comment]
@ControlAndC you should have a channel object and use `channel.sendMessage("message")` with it. See link to working demo app [above](https://github.com/twilio/TwilioChatJsReactNative/issues/49#issuecomment-649420273).

**Comment by ControlAndC** [comment]
@berkus

![image](https://user-images.githubusercontent.com/5564601/103774732-0b7a3c80-5053-11eb-8d66-797a24bde5ef.png)

`IS there anything wrong in the code, It is not working.`

**Comment by berkus** [comment]
I think that should work. What is the error?

**Comment by ControlAndC** [comment]
@berkus
`
    this.client.on('messageAdded', obj => this.log.event('ChatClientHelper.client', 'messageAdded', obj));

`
![image](https://user-images.githubusercontent.com/5564601/103777739-58601200-5057-11eb-97ab-72028b16d7cc.png)


Above callback is not getting called and even i have checked on Twilio DashBoard and message is not updated there.

**Comment by berkus** [comment]
I believe you get an error when trying to create the channel for the second time, you should handle that case.

Also enable SDK logs and it will be easier to understand what is going on in the app.

When creating the chat client, pass additional options object:

`Twilio.Chat.Client.create(token, { logLevel: 'debug' })`

**Comment by berkus** [comment]
Closing this one.
