### ISSUE TITLE
Migration to 1.4

### ISSUE THREAD

**Issue by RUIFERNANDE5** [twilio/TwilioChatJsReactNative#5]
Regarding [this email](https://www.twilio.com/docs/api/client/twilio-client-javascript-sdk-11-12-migration-guide), is there any plans on upgrading the npm package available?
Looks like [twilio-chat](https://www.npmjs.com/package/twilio-chat) is stuck on version 1.2.

Thanks in advance.

**Comment by aleksandrsivanovs** [comment]
this is example for twilio programmable chat.
current latest version for twilio-chat is 1.2.1 (https://www.npmjs.com/package/twilio-chat)

the email you are mentioning is about twilio-client :)
