### ISSUE TITLE
React Native Chat option not available?

### ISSUE THREAD

**Issue by umeshsgh82** [twilio/TwilioChatJsReactNative#53]
In this project how to chat in the app. After running the app it asks for Username and on submitting it shows the cosole logs. How to chat using this app?

Please help in providing some insights. Attaching screenshot of android reactive native chat js app.
![Screenshot](https://user-images.githubusercontent.com/69050931/92498755-a2a3c480-f218-11ea-8b54-105c7231786f.JPG)

**Comment by berkus** [comment]
You will need to implement the user interface and all other bits of the actual app. This is only framework integration demo.
