### ISSUE TITLE
Access and managing of few Twilio chat instances from any component of the react/react-native application

### ISSUE THREAD

**Issue by arthedza** [twilio/TwilioChatJsReactNative#57]
Is there any way to have access to a few Twilio chat instances from any component of the application? Or have access to them in the parent component at least? I've tried to use a Redux as a store for chat instances, channels, etc. but my redux dev tools had a memory leaking problem. I think the problem was in a complicated Twilio object's structure and his circular references. Anyway storing non-serializable structures in the Redux is a bad practice at all. In my project, I'm using react-navigation v5. Could it help me to deal with the problem?

**Comment by berkus** [comment]
Not sure what the question is about?

You can launch multiple SDKs with different tokens granting access to different Chat Instances iiuuc.

**Comment by berkus** [comment]
If you want to store things it's best to store only sids, not live objects. The objects are pretty heavy-weight and will not work well inside a redux store or similar. Afaik Frontline stores only sids in redux and accesses the actual objects using those identifiers when needed.

**Comment by mkilp** [comment]
@arthedza did you ever figure out a good way to store your messages? For me there seems to be a strong delay where the message history is being loaded from twilio.

**Comment by arthedza** [comment]
> @arthedza did you ever figure out a good way to store your messages? For me there seems to be a strong delay where the message history is being loaded from twilio.

I didn't store messages, I store whole chat instances in react context instead.
