### ISSUE TITLE
unable to run token- provider

### ISSUE THREAD

**Issue by faizanbuggy** [twilio/TwilioChatJsReactNative#74]
When I run the command npm run token-provider, firstly I get the message "Token provider listening on port 3002!" then I get the error "node:internal/process/promises:227 triggerUncaughtException(err, true /* fromPromise */); UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block or by rejecting a promise which was not handled with .catch()".

**Comment by InfiniteRain** [comment]
Hello, what version of Node are you on?

**Comment by faizanbuggy** [comment]
It's v15.5.0

**Comment by InfiniteRain** [comment]
Could you try downgrading to the LTS version (14.17) and see if it's any different? The lifecycle of promises got tweaked in the most recent versions of Node, which evidently tends to cause some issues.

**Comment by InfiniteRain** [comment]
Upon further investigation, I have located the exact part of code that is problematic. 

On line 47 of `app.js`, there's a part of code that connects to ngrok. If you add a `.catch` block to it, then your issue will be fixed regardless of the node version. We will fix this ASAP.

**Comment by berkus** [comment]
Fixed in #75 pls try updating and running again.

**Comment by berkus** [comment]
Please reopen if you still have this problem.
