### ISSUE TITLE
TwilsockUnavailableError causes crash because of missing Reflect

### ISSUE THREAD

**Issue by sam-vdp** [twilio/TwilioChatJsReactNative#8]
In certain error conditions `twilio-transport` throws `TwilsockUnavailableError`.

This tries to use `Reflect.construct` to build the error object, but the React Native JS environment does not have Reflect and thus the app crashes with:

`undefined is not a function (evaluating 'Reflect.construct(cls, Array.from(arguments))')`

**Comment by aleksandrsivanovs** [comment]
Thank you for the report. I'll take a look on Friday or early next week.
Meanwhile if you have a solution for this - please submit PR :)

Aleksandrs

**Comment by sam-vdp** [comment]
Thank you for investigating!

The TwilsockUnavailableError was triggered in my case by rapidly disconnecting and reconnecting the Twilio client, so it's not really something that should usually happen.

Installing a Reflect polyfill seems to work, I have used https://www.npmjs.com/package/es6-shim .
